Fix for #3835
quicwg/base-drafts pull request #4014
Opened 2020-08-19 13:17 UTC by larseggert

2020-08-19 22:09 UTC, ianswett commented
I also don't think this is necessary, but I'd like @martinthomson opinion

2020-08-20 00:28 UTC, martinthomson requested changes
I didn't want to do this.  I believe that more now that I've seen this.  These are both wrong, which demonstrates how this is non-trivial.  That's why this was originally limited to transitions.

2020-08-20 00:28 UTC, martinthomson commented on draft-ietf-quic-transport.md
> +          +-------+                       |
You receive STREAM frames here as well.

2020-08-20 00:28 UTC, martinthomson commented on draft-ietf-quic-transport.md
> +          +-------+<-- (optional) ----+-------+
And here, in case of reordering or spurious retransmission.

2020-08-20 00:28 UTC, martinthomson commented on draft-ietf-quic-transport.md
> +           +-------+                   +-------+
You send STREAM frames here too when packets get declared lost.

2020-08-20 03:41 UTC, janaiyengar commented
Right, the problem is that this PR doesn't exhaustively list all loops, but doing so will make this state machine unreadable and useless. The existing FSM shows transitions out of a state, not all the ones that keep the endpoint within that state.

2020-08-20 06:20 UTC, larseggert commented
I'm fine with dropping this - I just wanted to move the resolution along by preparing a PR that demonstrated (part of, I guess) the changes needed. @ekr?

2020-09-01 22:24 UTC, closed without merging