Proposed fix for #3987
quicwg/base-drafts pull request #4071
Opened 2020-09-03 12:50 UTC by larseggert

In the interest of helping move things along, here's a proposal for #3987.

2020-09-03 18:58 UTC, ianswett reviewed
I think we're using PTO in two cases because we want to allow time for the PTO to fire twice, but I could be wrong?

2020-09-04 06:15 UTC, larseggert commented
The issue that this is intending to address isn't about "why use a multiple of PTO for the timer" but "why use PTO, which includes max ACK delay, and not e.g. derive from SRTT". At least that is how I understood it...

2020-09-04 22:00 UTC, janaiyengar commented on draft-ietf-quic-transport.md
> +need to maintain a PTO value anyway.
```suggestion

Note:

: Using the PTO value here implicitly includes the peer's maximum expected
acknowledgement delay in the idle timeout period; see Section 6.2.1
of {{QUIC-RECOVERY}}. This ensures that the endpoint accounts for this
known peer delay before declaring the connection as idle and closing it.
```

2020-09-04 22:01 UTC, janaiyengar commented on draft-ietf-quic-transport.md
> +need to maintain a PTO value anyway.
This one is deliberate -- we want to account for max ack delay.

2020-09-04 22:05 UTC, janaiyengar commented on draft-ietf-quic-transport.md
> +value anyway.
```suggestion
(PTO) interval as defined in {{QUIC-RECOVERY}}.

Note:

: Using the PTO value here implicitly includes the peer's maximum expected
acknowledgement delay in the closing and draining periods; see Section 6.2.1
of {{QUIC-RECOVERY}}. This ensures that the endpoint takes this peer delay
into account when waiting to discard subsequent packets sent by the peer.
```

2020-09-07 23:04 UTC, ianswett commented
@larseggert in some cases, the reason for using PTO is to ensure there's time to PTO retransmit, so I don't think this change currently captures that reason in this cases.

I agree that's the basis of the issue as it stands, but I think the better question is why use PTO in different cases.  I think the max_ack_delay is not particularly interesting in any of these cases.

2020-09-07 23:05 UTC, ianswett requested changes
I don't think we need all this extra text on max_ack_delay in these cases, even if that's how the issue was filed.

2020-09-08 10:24 UTC, larseggert commented
I'm completely fine with not making changes. @Ralith?

2020-09-08 17:56 UTC, Ralith commented
Maybe just reduce it to the first case? My goal with the issue was make it explicit when we use PTO, including max_ack_delay, for the sake of simplicity even though max_ack_delay isn't actually pertinent. If it serves a legitimate purpose for idle/close timers, then there's less need to justify its involvement, because that involvement is less likely to produce confusion and give the impression of a spec bug.

2020-09-08 23:04 UTC, janaiyengar approved these changes

2020-09-08 23:07 UTC, martinthomson reviewed
I think that the document would be fine without any of these.  Certainly the latter two are a distraction.

2020-09-09 08:29 UTC, larseggert commented
OK, I rev'ed the PR to only include the first note. Do folks think this is OK, do we want changes, or do we want to drop if altogether?

2020-09-09 21:15 UTC, ianswett commented
I sent out an alternate PR: https://github.com/quicwg/base-drafts/pull/4084

2020-09-09 22:51 UTC, janaiyengar commented
@ianswett pointed out that the point here is not so much about including max_ack_delay, it is about using PTO values. Thinking about this, I agree. The idea here is to basically allow for the sender to retransmit the probe multiple times, and that happens on PTOs. Basically, I think what needs to be written is an explanation of the expression. My suggested explanation and text:

`6 x InitialRTT` ensures that the period is large enough for sending multiple PATH_CHALLENGE frames on initial timeout (with exponential backoff). `3 x PTO` ensures that _if the current path PTO is longer than `2 x InitialRTT`_  then we allow for the new path to be as long. If we want to clarify something here, that would be the point to clarify.

2020-09-09 22:53 UTC, janaiyengar commented
Uh, sorry, @ianswett : I posted my message and then saw your message (and PR) above. Looking now.

2020-09-10 01:49 UTC, closed without merging