Make references normative
quicwg/base-drafts pull request #4179
Opened 2020-10-02 20:37 UTC by janaiyengar

Closes #4178.

2020-10-04 13:49 UTC, ianswett approved these changes
I'm not the expert on what should be normative, but these were intentionally marked as informative references since they're all TCP specific RFCs.  The pipeACK reference in particular seems like an odd one.

If this is what the chairs want, then I'm ok with it as an editor, but these choices were intentional.

2020-10-05 20:43 UTC, martinduke requested changes
I see what @gloinul is saying, but I also see some wiggle room in RFC 3967, Section 1.1:

   -  When a reference to an example is made, such a reference need not
      be normative.  For example, text such as "an algorithm such as the
      one specified in [RFCxxxx] would be acceptable" indicates an
      informative reference, since that cited algorithm is just one of
      several possible algorithms that could be used.

I am also somewhat concerned that trying to get the downrefs into the registry is more likely to run into trouble (Sec 3)

This procedure should not be used if the proper step is to move the
   document to which the reference is being made into the appropriate
   category.  It is not intended as an easy way out of normal process.
   Rather, the procedure is intended for dealing with specific cases
   where putting particular documents into the required category is
   problematic and unlikely ever to happen.

Anyway, if we decide to proceed the PR is fine modulo my comment below.

2020-10-05 20:43 UTC, martinduke commented on draft-ietf-quic-recovery.md
> +Markings can be treated as equivalent to loss ({{!RFC3168}}), but other
This section doesn't have normative language, so I don't see a need for these references to be normative.

2020-10-06 01:32 UTC, martinthomson reviewed
I don't think that any of these need to be made normative either.  Each of these is exemplary only.

2020-10-07 12:16 UTC, ianswett requested changes
Removing my approval, since I don't really want to make this change and it appears others have similar opinions and letting the conversation on the issue play out.

2020-10-12 20:05 UTC, janaiyengar commented
Closing in favor of #4190

2020-10-12 20:05 UTC, closed without merging