update refs for -12 of http core drafts
quicwg/base-drafts pull request #4182
Opened 2020-10-04 15:25 UTC by reschke

2020-10-07 19:52 UTC, MikeBishop requested changes
Thanks for doing this scrub, Julian.  A few things here where I think there might be a more appropriate reference.

2020-10-07 19:52 UTC, MikeBishop commented on draft-ietf-quic-http.md
> +authoritative server for an HTTP URL is discussed in Section 6.1.3 of
```suggestion
authoritative server for an HTTP URL is discussed in Section 4.3 of
```

2020-10-07 19:52 UTC, MikeBishop commented on draft-ietf-quic-http.md
> +authoritative for origins containing that hostname or address.  See Section 6.1.3
```suggestion
authoritative for origins containing that hostname or address.  See Section 4.3
```

2020-10-07 19:52 UTC, MikeBishop commented on draft-ietf-quic-http.md
> +Header and trailer field sections are described in Section 5.4 of {{!SEMANTICS}};
Section 5.4 is about headers only, not trailers.  This may need to explicitly reference 5.4 and 5.6 to get the equivalent context.

2020-10-07 19:52 UTC, MikeBishop commented on draft-ietf-quic-http.md
> +payload, as described in Section 5.5.4 of {{!SEMANTICS}} can have a non-zero
```suggestion
payload, as described in Section 5.5.4 of {{!SEMANTICS}}, can have a non-zero
```
Not an error in your PR, just an existing error you happened to touch.

2020-10-07 19:55 UTC, MikeBishop commented on draft-ietf-quic-http.md
> +field names in the syntax used by HTTP (Section 5.4.3 of {{!SEMANTICS}}). Requests
This paragraph needs to be rewrapped.

2020-10-15 10:19 UTC, LPardue commented
@reschke could you please help us out by responding to Mike's comments. This PR you kindly made will help us address issues raised during AD review, which is a blocker to LC.

2020-10-16 06:21 UTC, larseggert commented
If @reschke isn't responding, @MikeBishop should use his best judgement and then merge this.

2020-10-16 06:29 UTC, reschke commented
I only did a mechanical check (restoring the references that were there before). @MikeBishop - if you feel that these can be improved just go ahead.

2020-10-16 15:23 UTC, MikeBishop commented on draft-ietf-quic-http.md
> +the payload body is described in Section 5.5.4 of {{!SEMANTICS}}.
```suggestion
Header and trailer field sections are described in Sections 5.4 and 5.6 of
{{!SEMANTICS}}; the payload body is described in Section 5.5.4 of
{{!SEMANTICS}}.
```

2020-10-16 15:29 UTC, merged