Always save the packet size and return early
quicwg/base-drafts pull request #4409
Opened 2020-11-25 02:09 UTC by ianswett

When the packet is not in_flight, return early instead of not saving the size earlier.

FIxes #4408

2020-11-25 03:55 UTC, janaiyengar requested changes
This is an improvement; thanks for working on it! You do need to check for `in_flight` in `OnPacketsLost()` as well where `sent_bytes` is subtracted from `bytes_in_flight`.

2020-11-25 03:55 UTC, janaiyengar commented on draft-ietf-quic-recovery.md
> +  if (!ack_packet.in_flight):
```suggestion
  if (!acked_packet.in_flight):
```

2020-11-25 14:45 UTC, ianswett commented
We already have a check to only add in_flight packets to lost_packets, but I added an assert to hopefully make that clearer.

2020-11-26 00:08 UTC, janaiyengar approved these changes
I think symmetry here would have been clearer -- if all lost packets were in the list, similar to acked packets, and if the check for inflight was at the time of removing it from bytes_in_flight. That does make the code for OnPacketsLost more complicated though, since you have to do an early return if none of the packets lost were in flight. On balance, I think the assert is good enough -- thanks!

2020-11-26 00:08 UTC, merged