Fix confusing indexing name
quicwg/base-drafts pull request #4933
Opened 2021-08-05 06:53 UTC by ami-GS

`absolute index` could make sense, but `Indexed Field Line` and `Literal Field Line With Name Reference` are better to use  `relative index`, because these are said as `relative index` when T=0 at line 1043 and 1098.
`post base index` as well. it would be better than `absolute index`.
Line 585 said this index as `Unlike in encoder instructions,  relative indices in field line representations are relative to the Base at the beginning of the encoded field section`

2021-08-05 14:15 UTC, MikeBishop requested changes
None of these changes are correct.  The point of the absolute index is that it's not changing -- these are the definitions of how other types of references map to an absolute index, and which absolute indices can be expressed by each reference type.

2021-08-05 14:15 UTC, MikeBishop commented on draft-ietf-quic-qpack.md
> +or an entry in the dynamic table with an relative index less than the value of
No; the Base is an absolute index.  An Indexed Field Line of this type uses relative indices, and so can only reference a certain region of the table; this is describing which region.

2021-08-05 14:15 UTC, MikeBishop commented on draft-ietf-quic-qpack.md
> +in the dynamic table with an post base index greater than or equal to the value
Same here -- it makes no sense to say that the post-base index is greater than or equal to the value of the Base.

2021-08-10 06:27 UTC, ami-GS commented
How about this? should make sense more

2021-08-10 16:55 UTC, afrind commented
The opening text for each representation is trying to state which dynamic table entries are eligible for for that representation.  All three representations state that they include either a relative or post-base index in the paragraph following the diagram.

The eligibility condition is awkward because "Base" really means "Base Insert Count".  Comparing indexes and counts can get confusing - eg: Absolute Index = 0 can be used in Indexed Field Line when Base (count) is 1 or greater. 

So the explanation in the draft works better for me than the proposed text, but I don't love it.  I'm inclined not to merge this PR.

2021-08-11 18:18 UTC, MikeBishop commented
1024 is a blank line, so I'm guessing you meant a different line number.  1043, maybe?

I think the confusion is that they're *not* describing the same thing with opposite adjectives; they're describing related but different concepts.
- Every entry that has ever been in the table has an absolute index; see 3.2.4.  Because this number grows over time, it's never directly used on the wire.  It's an internal reference in each implementation.
- In order to compress this potentially-large value, it's expressed on the wire as a relative index or a post-base index; see 3.2.5 and 3.2.6.
- To turn a relative or post-base index into an absolute index and look up the appropriate item, you start from the most recent entry (on the Encoder stream) or the Base (within encoded field sections) and count one direction or the other.
- The different representation types can only refer to a certain region of absolute indices relative to the Base; each representation describes the range it is able to reference at the beginning of its description.  (e.g. `an entry ... with an absolute index less than the value of the Base`)

So every entry has an absolute index, but no instructions use absolute indices.  Instead, they use relative indices.  A decoder will first resolve a relative index into an absolute index, then look up that location in the table.

2021-08-18 08:00 UTC, ami-GS commented
Maybe I get the point (Yes, line 1043 is correct)
The `absolute index` in `absolute index ... the value of the Base.` doesn't talk about index written in wire, right?
Just a general concept about absolute index used to refer entry and how is it relative Base for each field section type.

2021-08-18 14:57 UTC, MikeBishop commented
Right -- the absolute index is a concept used to describe how things work, but is never used directly on the wire.

2021-08-18 20:55 UTC, closed without merging